"""cambiar constraint encuestas a pedido_producto

Revision ID: 20584798f66f
Revises: 20250124
Create Date: 2026-04-26 08:52:30.116933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20584798f66f'
down_revision: Union[str, None] = '20250124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Migración idempotente: la BD de producción puede haber sido modificada
    # manualmente (ver scripts/migrar_constraint_encuestas.py), así que verificamos
    # el estado antes de cada operación destructiva.
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    existing_tables = set(inspector.get_table_names())
    for tbl in ('carrito_items', 'carritos', 'items_carrito', 'carrito_compras'):
        if tbl in existing_tables:
            op.drop_table(tbl)

    if 'encuestas_satisfaccion' in existing_tables:
        enc_cols = {c['name']: c for c in inspector.get_columns('encuestas_satisfaccion')}
        if 'producto_id' in enc_cols and enc_cols['producto_id'].get('nullable', True):
            op.alter_column('encuestas_satisfaccion', 'producto_id',
                            existing_type=sa.INTEGER(), nullable=False)

        enc_uniques = {uc['name'] for uc in inspector.get_unique_constraints('encuestas_satisfaccion')}
        if 'encuestas_satisfaccion_pedido_id_key' in enc_uniques:
            op.drop_constraint('encuestas_satisfaccion_pedido_id_key',
                               'encuestas_satisfaccion', type_='unique')
        if 'unique_pedido_producto' not in enc_uniques:
            op.create_unique_constraint('unique_pedido_producto',
                                        'encuestas_satisfaccion',
                                        ['pedido_id', 'producto_id'])

    if 'pedidos' in existing_tables:
        pedido_cols = {c['name'] for c in inspector.get_columns('pedidos')}
        if 'direccion_envio' in pedido_cols:
            op.drop_column('pedidos', 'direccion_envio')

    if 'productos' in existing_tables:
        prod_cols = {c['name']: c for c in inspector.get_columns('productos')}
        if 'talla' in prod_cols:
            # Solo reducimos a VARCHAR(10) si todos los datos caben.
            # Si hay valores >10 chars (drift histórico), mantenemos el tamaño
            # actual: VARCHAR(35) no rompe el runtime, solo es más permisivo.
            max_len = bind.execute(
                sa.text("SELECT COALESCE(MAX(LENGTH(talla)), 0) FROM productos")
            ).scalar() or 0
            if max_len <= 10:
                op.alter_column('productos', 'talla',
                                existing_type=sa.VARCHAR(length=35),
                                type_=sa.String(length=10),
                                existing_nullable=True)
        if 'stock' in prod_cols and prod_cols['stock'].get('nullable', True):
            op.alter_column('productos', 'stock',
                            existing_type=sa.SMALLINT(),
                            type_=sa.Integer(),
                            nullable=False)

    if 'usuarios' in existing_tables:
        usuario_cols = {c['name'] for c in inspector.get_columns('usuarios')}
        if 'nit' in usuario_cols:
            op.drop_column('usuarios', 'nit')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('productos', 'stock',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=True)
    op.alter_column('productos', 'talla',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=35),
               existing_nullable=True)
    op.add_column('pedidos', sa.Column('direccion_envio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('unique_pedido_producto', 'encuestas_satisfaccion', type_='unique')
    op.create_unique_constraint(op.f('encuestas_satisfaccion_pedido_id_key'), 'encuestas_satisfaccion', ['pedido_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('encuestas_satisfaccion', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('carrito_compras',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('carrito_compras_cliente_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('carrito_compras_pkey')),
    sa.UniqueConstraint('cliente_id', name=op.f('carrito_compras_cliente_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_carrito_compras_id'), 'carrito_compras', ['id'], unique=False)
    op.create_table('items_carrito',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('carrito_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('agregado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carrito_compras.id'], name=op.f('items_carrito_carrito_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('items_carrito_producto_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('items_carrito_pkey'))
    )
    op.create_index(op.f('ix_items_carrito_id'), 'items_carrito', ['id'], unique=False)
    op.create_table('carritos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('carritos_cliente_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('carritos_pkey'))
    )
    op.create_index(op.f('ix_carritos_id'), 'carritos', ['id'], unique=False)
    op.create_table('carrito_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carrito_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carritos.id'], name=op.f('carrito_items_carrito_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('carrito_items_producto_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('carrito_items_pkey'))
    )
    op.create_index(op.f('ix_carrito_items_id'), 'carrito_items', ['id'], unique=False)
    # ### end Alembic commands ###
