"""cambiar constraint encuestas a pedido_producto

Revision ID: 20584798f66f
Revises: 20250124
Create Date: 2026-04-26 08:52:30.116933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20584798f66f'
down_revision: Union[str, None] = '20250124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carrito_items_id'), table_name='carrito_items')
    op.drop_table('carrito_items')
    op.drop_index(op.f('ix_carritos_id'), table_name='carritos')
    op.drop_table('carritos')
    op.drop_index(op.f('ix_items_carrito_id'), table_name='items_carrito')
    op.drop_table('items_carrito')
    op.drop_index(op.f('ix_carrito_compras_id'), table_name='carrito_compras')
    op.drop_table('carrito_compras')
    op.alter_column('encuestas_satisfaccion', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('encuestas_satisfaccion_pedido_id_key'), 'encuestas_satisfaccion', type_='unique')
    op.create_unique_constraint('unique_pedido_producto', 'encuestas_satisfaccion', ['pedido_id', 'producto_id'])
    op.drop_column('pedidos', 'direccion_envio')
    op.alter_column('productos', 'talla',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('productos', 'stock',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_column('usuarios', 'nit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('productos', 'stock',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=True)
    op.alter_column('productos', 'talla',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=35),
               existing_nullable=True)
    op.add_column('pedidos', sa.Column('direccion_envio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('unique_pedido_producto', 'encuestas_satisfaccion', type_='unique')
    op.create_unique_constraint(op.f('encuestas_satisfaccion_pedido_id_key'), 'encuestas_satisfaccion', ['pedido_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('encuestas_satisfaccion', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('carrito_compras',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('carrito_compras_cliente_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('carrito_compras_pkey')),
    sa.UniqueConstraint('cliente_id', name=op.f('carrito_compras_cliente_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_carrito_compras_id'), 'carrito_compras', ['id'], unique=False)
    op.create_table('items_carrito',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('carrito_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('agregado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carrito_compras.id'], name=op.f('items_carrito_carrito_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('items_carrito_producto_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('items_carrito_pkey'))
    )
    op.create_index(op.f('ix_items_carrito_id'), 'items_carrito', ['id'], unique=False)
    op.create_table('carritos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('carritos_cliente_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('carritos_pkey'))
    )
    op.create_index(op.f('ix_carritos_id'), 'carritos', ['id'], unique=False)
    op.create_table('carrito_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carrito_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carritos.id'], name=op.f('carrito_items_carrito_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('carrito_items_producto_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('carrito_items_pkey'))
    )
    op.create_index(op.f('ix_carrito_items_id'), 'carrito_items', ['id'], unique=False)
    # ### end Alembic commands ###
